name: business_card
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/ai.png
  fonts:
    - family: Lobster Two
      fonts:
        - asset: lib/LobsterTwo-Bold.ttf
        - asset: lib/LobsterTwo-BoldItalic.ttf
        - asset: lib/LobsterTwo-Italic.ttf
        - asset: lib/LobsterTwo-Regular.ttf